// Code generated by 'goexports gonum.org/v1/gonum/graph/formats/sigmajs'. DO NOT EDIT.

// Copyright ©2019 The Gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// +build go1.12,!go1.13

package yaegi

import (
	"reflect"

	"gonum.org/v1/gonum/graph/formats/sigmajs"
)

func init() {
	Symbols["gonum.org/v1/gonum/graph/formats/sigmajs"] = map[string]reflect.Value{
		// type definitions
		"Edge":  reflect.ValueOf((*sigmajs.Edge)(nil)),
		"Graph": reflect.ValueOf((*sigmajs.Graph)(nil)),
		"Node":  reflect.ValueOf((*sigmajs.Node)(nil)),
	}
}
