// Code generated by 'goexports gonum.org/v1/gonum/stat/mds'. DO NOT EDIT.

// Copyright ©2019 The Gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// +build go1.14,!go1.15

package yaegi

import (
	"reflect"

	"gonum.org/v1/gonum/stat/mds"
)

func init() {
	Symbols["gonum.org/v1/gonum/stat/mds"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"TorgersonScaling": reflect.ValueOf(mds.TorgersonScaling),
	}
}
