// Code generated by 'github.com/containous/yaegi/extract gonum.org/v1/gonum/blas/gonum'. DO NOT EDIT.

// Copyright ©2019 The Gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// +build go1.15,!go1.16

package yaegi

import (
	"reflect"

	"gonum.org/v1/gonum/blas/gonum"
)

func init() {
	Symbols["gonum.org/v1/gonum/blas/gonum"] = map[string]reflect.Value{
		// type definitions
		"Implementation": reflect.ValueOf((*gonum.Implementation)(nil)),
	}
}
