// Code generated by 'goexports gonum.org/v1/gonum/blas/cblas128'. DO NOT EDIT.

// Copyright ©2019 The Gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build go1.14 && !go1.15
// +build go1.14,!go1.15

package yaegi

import (
	"reflect"

	"gonum.org/v1/gonum/blas/cblas128"
)

func init() {
	Symbols["gonum.org/v1/gonum/blas/cblas128"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Asum":           reflect.ValueOf(cblas128.Asum),
		"Axpy":           reflect.ValueOf(cblas128.Axpy),
		"Copy":           reflect.ValueOf(cblas128.Copy),
		"Dotc":           reflect.ValueOf(cblas128.Dotc),
		"Dotu":           reflect.ValueOf(cblas128.Dotu),
		"Dscal":          reflect.ValueOf(cblas128.Dscal),
		"Gbmv":           reflect.ValueOf(cblas128.Gbmv),
		"Gemm":           reflect.ValueOf(cblas128.Gemm),
		"Gemv":           reflect.ValueOf(cblas128.Gemv),
		"Gerc":           reflect.ValueOf(cblas128.Gerc),
		"Geru":           reflect.ValueOf(cblas128.Geru),
		"Hbmv":           reflect.ValueOf(cblas128.Hbmv),
		"Hemm":           reflect.ValueOf(cblas128.Hemm),
		"Hemv":           reflect.ValueOf(cblas128.Hemv),
		"Her":            reflect.ValueOf(cblas128.Her),
		"Her2":           reflect.ValueOf(cblas128.Her2),
		"Her2k":          reflect.ValueOf(cblas128.Her2k),
		"Herk":           reflect.ValueOf(cblas128.Herk),
		"Hpmv":           reflect.ValueOf(cblas128.Hpmv),
		"Hpr":            reflect.ValueOf(cblas128.Hpr),
		"Hpr2":           reflect.ValueOf(cblas128.Hpr2),
		"Iamax":          reflect.ValueOf(cblas128.Iamax),
		"Implementation": reflect.ValueOf(cblas128.Implementation),
		"Nrm2":           reflect.ValueOf(cblas128.Nrm2),
		"Scal":           reflect.ValueOf(cblas128.Scal),
		"Swap":           reflect.ValueOf(cblas128.Swap),
		"Symm":           reflect.ValueOf(cblas128.Symm),
		"Syr2k":          reflect.ValueOf(cblas128.Syr2k),
		"Syrk":           reflect.ValueOf(cblas128.Syrk),
		"Tbmv":           reflect.ValueOf(cblas128.Tbmv),
		"Tbsv":           reflect.ValueOf(cblas128.Tbsv),
		"Tpmv":           reflect.ValueOf(cblas128.Tpmv),
		"Tpsv":           reflect.ValueOf(cblas128.Tpsv),
		"Trmm":           reflect.ValueOf(cblas128.Trmm),
		"Trmv":           reflect.ValueOf(cblas128.Trmv),
		"Trsm":           reflect.ValueOf(cblas128.Trsm),
		"Trsv":           reflect.ValueOf(cblas128.Trsv),
		"Use":            reflect.ValueOf(cblas128.Use),

		// type definitions
		"Band":               reflect.ValueOf((*cblas128.Band)(nil)),
		"BandCols":           reflect.ValueOf((*cblas128.BandCols)(nil)),
		"General":            reflect.ValueOf((*cblas128.General)(nil)),
		"GeneralCols":        reflect.ValueOf((*cblas128.GeneralCols)(nil)),
		"Hermitian":          reflect.ValueOf((*cblas128.Hermitian)(nil)),
		"HermitianBand":      reflect.ValueOf((*cblas128.HermitianBand)(nil)),
		"HermitianBandCols":  reflect.ValueOf((*cblas128.HermitianBandCols)(nil)),
		"HermitianCols":      reflect.ValueOf((*cblas128.HermitianCols)(nil)),
		"HermitianPacked":    reflect.ValueOf((*cblas128.HermitianPacked)(nil)),
		"Symmetric":          reflect.ValueOf((*cblas128.Symmetric)(nil)),
		"SymmetricBand":      reflect.ValueOf((*cblas128.SymmetricBand)(nil)),
		"SymmetricBandCols":  reflect.ValueOf((*cblas128.SymmetricBandCols)(nil)),
		"SymmetricCols":      reflect.ValueOf((*cblas128.SymmetricCols)(nil)),
		"SymmetricPacked":    reflect.ValueOf((*cblas128.SymmetricPacked)(nil)),
		"Triangular":         reflect.ValueOf((*cblas128.Triangular)(nil)),
		"TriangularBand":     reflect.ValueOf((*cblas128.TriangularBand)(nil)),
		"TriangularBandCols": reflect.ValueOf((*cblas128.TriangularBandCols)(nil)),
		"TriangularCols":     reflect.ValueOf((*cblas128.TriangularCols)(nil)),
		"TriangularPacked":   reflect.ValueOf((*cblas128.TriangularPacked)(nil)),
		"Vector":             reflect.ValueOf((*cblas128.Vector)(nil)),
	}
}
