// Code generated by 'goexports gonum.org/v1/gonum/graph/community'. DO NOT EDIT.

// Copyright ©2019 The Gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build go1.14 && !go1.15
// +build go1.14,!go1.15

package yaegi

import (
	"reflect"

	"gonum.org/v1/gonum/graph"
	"gonum.org/v1/gonum/graph/community"
)

func init() {
	Symbols["gonum.org/v1/gonum/graph/community"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"KCliqueCommunities":    reflect.ValueOf(community.KCliqueCommunities),
		"ModularMultiplexScore": reflect.ValueOf(community.ModularMultiplexScore),
		"ModularScore":          reflect.ValueOf(community.ModularScore),
		"Modularize":            reflect.ValueOf(community.Modularize),
		"ModularizeMultiplex":   reflect.ValueOf(community.ModularizeMultiplex),
		"NewDirectedLayers":     reflect.ValueOf(community.NewDirectedLayers),
		"NewUndirectedLayers":   reflect.ValueOf(community.NewUndirectedLayers),
		"Profile":               reflect.ValueOf(community.Profile),
		"Q":                     reflect.ValueOf(community.Q),
		"QMultiplex":            reflect.ValueOf(community.QMultiplex),
		"Size":                  reflect.ValueOf(community.Size),
		"SizeMultiplex":         reflect.ValueOf(community.SizeMultiplex),
		"Weight":                reflect.ValueOf(community.Weight),
		"WeightMultiplex":       reflect.ValueOf(community.WeightMultiplex),

		// type definitions
		"DirectedLayers":             reflect.ValueOf((*community.DirectedLayers)(nil)),
		"DirectedMultiplex":          reflect.ValueOf((*community.DirectedMultiplex)(nil)),
		"Interval":                   reflect.ValueOf((*community.Interval)(nil)),
		"Multiplex":                  reflect.ValueOf((*community.Multiplex)(nil)),
		"Reduced":                    reflect.ValueOf((*community.Reduced)(nil)),
		"ReducedDirected":            reflect.ValueOf((*community.ReducedDirected)(nil)),
		"ReducedDirectedMultiplex":   reflect.ValueOf((*community.ReducedDirectedMultiplex)(nil)),
		"ReducedGraph":               reflect.ValueOf((*community.ReducedGraph)(nil)),
		"ReducedMultiplex":           reflect.ValueOf((*community.ReducedMultiplex)(nil)),
		"ReducedUndirected":          reflect.ValueOf((*community.ReducedUndirected)(nil)),
		"ReducedUndirectedMultiplex": reflect.ValueOf((*community.ReducedUndirectedMultiplex)(nil)),
		"UndirectedLayers":           reflect.ValueOf((*community.UndirectedLayers)(nil)),
		"UndirectedMultiplex":        reflect.ValueOf((*community.UndirectedMultiplex)(nil)),

		// interface wrapper definitions
		"_DirectedMultiplex":   reflect.ValueOf((*_gonum_org_v1_gonum_graph_community_DirectedMultiplex)(nil)),
		"_Multiplex":           reflect.ValueOf((*_gonum_org_v1_gonum_graph_community_Multiplex)(nil)),
		"_Reduced":             reflect.ValueOf((*_gonum_org_v1_gonum_graph_community_Reduced)(nil)),
		"_ReducedGraph":        reflect.ValueOf((*_gonum_org_v1_gonum_graph_community_ReducedGraph)(nil)),
		"_ReducedMultiplex":    reflect.ValueOf((*_gonum_org_v1_gonum_graph_community_ReducedMultiplex)(nil)),
		"_UndirectedMultiplex": reflect.ValueOf((*_gonum_org_v1_gonum_graph_community_UndirectedMultiplex)(nil)),
	}
}

// _gonum_org_v1_gonum_graph_community_DirectedMultiplex is an interface wrapper for DirectedMultiplex type
type _gonum_org_v1_gonum_graph_community_DirectedMultiplex struct {
	WDepth func() int
	WLayer func(l int) graph.Directed
	WNodes func() graph.Nodes
}

func (W _gonum_org_v1_gonum_graph_community_DirectedMultiplex) Depth() int { return W.WDepth() }
func (W _gonum_org_v1_gonum_graph_community_DirectedMultiplex) Layer(l int) graph.Directed {
	return W.WLayer(l)
}
func (W _gonum_org_v1_gonum_graph_community_DirectedMultiplex) Nodes() graph.Nodes { return W.WNodes() }

// _gonum_org_v1_gonum_graph_community_Multiplex is an interface wrapper for Multiplex type
type _gonum_org_v1_gonum_graph_community_Multiplex struct {
	WDepth func() int
	WNodes func() graph.Nodes
}

func (W _gonum_org_v1_gonum_graph_community_Multiplex) Depth() int         { return W.WDepth() }
func (W _gonum_org_v1_gonum_graph_community_Multiplex) Nodes() graph.Nodes { return W.WNodes() }

// _gonum_org_v1_gonum_graph_community_Reduced is an interface wrapper for Reduced type
type _gonum_org_v1_gonum_graph_community_Reduced struct {
	WCommunities func() [][]graph.Node
}

func (W _gonum_org_v1_gonum_graph_community_Reduced) Communities() [][]graph.Node {
	return W.WCommunities()
}

// _gonum_org_v1_gonum_graph_community_ReducedGraph is an interface wrapper for ReducedGraph type
type _gonum_org_v1_gonum_graph_community_ReducedGraph struct {
	WCommunities    func() [][]graph.Node
	WEdge           func(uid int64, vid int64) graph.Edge
	WExpanded       func() community.ReducedGraph
	WFrom           func(id int64) graph.Nodes
	WHasEdgeBetween func(xid int64, yid int64) bool
	WNode           func(id int64) graph.Node
	WNodes          func() graph.Nodes
	WStructure      func() [][]graph.Node
}

func (W _gonum_org_v1_gonum_graph_community_ReducedGraph) Communities() [][]graph.Node {
	return W.WCommunities()
}
func (W _gonum_org_v1_gonum_graph_community_ReducedGraph) Edge(uid int64, vid int64) graph.Edge {
	return W.WEdge(uid, vid)
}
func (W _gonum_org_v1_gonum_graph_community_ReducedGraph) Expanded() community.ReducedGraph {
	return W.WExpanded()
}
func (W _gonum_org_v1_gonum_graph_community_ReducedGraph) From(id int64) graph.Nodes {
	return W.WFrom(id)
}
func (W _gonum_org_v1_gonum_graph_community_ReducedGraph) HasEdgeBetween(xid int64, yid int64) bool {
	return W.WHasEdgeBetween(xid, yid)
}
func (W _gonum_org_v1_gonum_graph_community_ReducedGraph) Node(id int64) graph.Node {
	return W.WNode(id)
}
func (W _gonum_org_v1_gonum_graph_community_ReducedGraph) Nodes() graph.Nodes { return W.WNodes() }
func (W _gonum_org_v1_gonum_graph_community_ReducedGraph) Structure() [][]graph.Node {
	return W.WStructure()
}

// _gonum_org_v1_gonum_graph_community_ReducedMultiplex is an interface wrapper for ReducedMultiplex type
type _gonum_org_v1_gonum_graph_community_ReducedMultiplex struct {
	WCommunities func() [][]graph.Node
	WDepth       func() int
	WExpanded    func() community.ReducedMultiplex
	WNodes       func() graph.Nodes
	WStructure   func() [][]graph.Node
}

func (W _gonum_org_v1_gonum_graph_community_ReducedMultiplex) Communities() [][]graph.Node {
	return W.WCommunities()
}
func (W _gonum_org_v1_gonum_graph_community_ReducedMultiplex) Depth() int { return W.WDepth() }
func (W _gonum_org_v1_gonum_graph_community_ReducedMultiplex) Expanded() community.ReducedMultiplex {
	return W.WExpanded()
}
func (W _gonum_org_v1_gonum_graph_community_ReducedMultiplex) Nodes() graph.Nodes { return W.WNodes() }
func (W _gonum_org_v1_gonum_graph_community_ReducedMultiplex) Structure() [][]graph.Node {
	return W.WStructure()
}

// _gonum_org_v1_gonum_graph_community_UndirectedMultiplex is an interface wrapper for UndirectedMultiplex type
type _gonum_org_v1_gonum_graph_community_UndirectedMultiplex struct {
	WDepth func() int
	WLayer func(l int) graph.Undirected
	WNodes func() graph.Nodes
}

func (W _gonum_org_v1_gonum_graph_community_UndirectedMultiplex) Depth() int { return W.WDepth() }
func (W _gonum_org_v1_gonum_graph_community_UndirectedMultiplex) Layer(l int) graph.Undirected {
	return W.WLayer(l)
}
func (W _gonum_org_v1_gonum_graph_community_UndirectedMultiplex) Nodes() graph.Nodes {
	return W.WNodes()
}
