// Code generated by 'goexports gonum.org/v1/gonum/spatial/r2'. DO NOT EDIT.

// Copyright ©2019 The Gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build go1.14 && !go1.15
// +build go1.14,!go1.15

package yaegi

import (
	"reflect"

	"gonum.org/v1/gonum/spatial/r2"
)

func init() {
	Symbols["gonum.org/v1/gonum/spatial/r2"] = map[string]reflect.Value{
		// type definitions
		"Box": reflect.ValueOf((*r2.Box)(nil)),
		"Vec": reflect.ValueOf((*r2.Vec)(nil)),
	}
}
