// Code generated by 'github.com/containous/yaegi/extract gonum.org/v1/gonum/mathext/prng'. DO NOT EDIT.

// Copyright ©2019 The Gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// +build go1.15,!go1.16

package yaegi

import (
	"reflect"

	"gonum.org/v1/gonum/mathext/prng"
)

func init() {
	Symbols["gonum.org/v1/gonum/mathext/prng"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewMT19937":            reflect.ValueOf(prng.NewMT19937),
		"NewMT19937_64":         reflect.ValueOf(prng.NewMT19937_64),
		"NewSplitMix64":         reflect.ValueOf(prng.NewSplitMix64),
		"NewXoshiro256plus":     reflect.ValueOf(prng.NewXoshiro256plus),
		"NewXoshiro256plusplus": reflect.ValueOf(prng.NewXoshiro256plusplus),
		"NewXoshiro256starstar": reflect.ValueOf(prng.NewXoshiro256starstar),

		// type definitions
		"MT19937":            reflect.ValueOf((*prng.MT19937)(nil)),
		"MT19937_64":         reflect.ValueOf((*prng.MT19937_64)(nil)),
		"SplitMix64":         reflect.ValueOf((*prng.SplitMix64)(nil)),
		"Xoshiro256plus":     reflect.ValueOf((*prng.Xoshiro256plus)(nil)),
		"Xoshiro256plusplus": reflect.ValueOf((*prng.Xoshiro256plusplus)(nil)),
		"Xoshiro256starstar": reflect.ValueOf((*prng.Xoshiro256starstar)(nil)),
	}
}
