// Code generated by 'goexports gonum.org/v1/gonum/graph/encoding/graph6'. DO NOT EDIT.

// Copyright ©2019 The Gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// +build go1.14,!go1.15

package yaegi

import (
	"reflect"

	"gonum.org/v1/gonum/graph/encoding/graph6"
)

func init() {
	Symbols["gonum.org/v1/gonum/graph/encoding/graph6"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Encode":  reflect.ValueOf(graph6.Encode),
		"IsValid": reflect.ValueOf(graph6.IsValid),

		// type definitions
		"Graph": reflect.ValueOf((*graph6.Graph)(nil)),
	}
}
