// Code generated by 'github.com/containous/yaegi/extract gonum.org/v1/gonum/unit'. DO NOT EDIT.

// Copyright ©2019 The Gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// +build go1.15,!go1.16

package yaegi

import (
	"go/constant"
	"go/token"
	"reflect"

	"gonum.org/v1/gonum/unit"
)

func init() {
	Symbols["gonum.org/v1/gonum/unit"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Ampere":               reflect.ValueOf(unit.Ampere),
		"AngleDim":             reflect.ValueOf(unit.AngleDim),
		"Atto":                 reflect.ValueOf(constant.MakeFromLiteral("9.999999999999999999783279765610610233913757988329308605702773439e-19", token.FLOAT, 0)),
		"Becquerel":            reflect.ValueOf(unit.Becquerel),
		"Candela":              reflect.ValueOf(unit.Candela),
		"Centi":                reflect.ValueOf(constant.MakeFromLiteral("0.009999999999999999999796712092658967918623602599836885929107666016", token.FLOAT, 0)),
		"Coulomb":              reflect.ValueOf(unit.Coulomb),
		"CurrentDim":           reflect.ValueOf(unit.CurrentDim),
		"Deca":                 reflect.ValueOf(constant.MakeFromLiteral("10", token.FLOAT, 0)),
		"Deci":                 reflect.ValueOf(constant.MakeFromLiteral("0.1000000000000000000013552527156068805425093160010874271392822266", token.FLOAT, 0)),
		"DimensionsMatch":      reflect.ValueOf(unit.DimensionsMatch),
		"Exa":                  reflect.ValueOf(constant.MakeFromLiteral("1000000000000000000", token.FLOAT, 0)),
		"Farad":                reflect.ValueOf(unit.Farad),
		"Femto":                reflect.ValueOf(constant.MakeFromLiteral("9.99999999999999999994126620636112567498475617893197842480160209e-16", token.FLOAT, 0)),
		"Giga":                 reflect.ValueOf(constant.MakeFromLiteral("1000000000", token.FLOAT, 0)),
		"Gram":                 reflect.ValueOf(unit.Gram),
		"Gray":                 reflect.ValueOf(unit.Gray),
		"Hecto":                reflect.ValueOf(constant.MakeFromLiteral("100", token.FLOAT, 0)),
		"Henry":                reflect.ValueOf(unit.Henry),
		"Hertz":                reflect.ValueOf(unit.Hertz),
		"Hour":                 reflect.ValueOf(unit.Hour),
		"Joule":                reflect.ValueOf(unit.Joule),
		"Kelvin":               reflect.ValueOf(unit.Kelvin),
		"Kilo":                 reflect.ValueOf(constant.MakeFromLiteral("1000", token.FLOAT, 0)),
		"Kilogram":             reflect.ValueOf(unit.Kilogram),
		"LengthDim":            reflect.ValueOf(unit.LengthDim),
		"Litre":                reflect.ValueOf(unit.Litre),
		"LuminousIntensityDim": reflect.ValueOf(unit.LuminousIntensityDim),
		"MassDim":              reflect.ValueOf(unit.MassDim),
		"Mega":                 reflect.ValueOf(constant.MakeFromLiteral("1000000", token.FLOAT, 0)),
		"Metre":                reflect.ValueOf(unit.Metre),
		"Micro":                reflect.ValueOf(constant.MakeFromLiteral("1.00000000000000000003625036316452388482356461452127405209466815e-06", token.FLOAT, 0)),
		"Milli":                reflect.ValueOf(constant.MakeFromLiteral("0.0009999999999999999999584953855845392833856521974666975438594818115", token.FLOAT, 0)),
		"Minute":               reflect.ValueOf(unit.Minute),
		"Mol":                  reflect.ValueOf(unit.Mol),
		"MoleDim":              reflect.ValueOf(unit.MoleDim),
		"Nano":                 reflect.ValueOf(constant.MakeFromLiteral("9.999999999999999999805126070452280747003935210126535082508780761e-10", token.FLOAT, 0)),
		"New":                  reflect.ValueOf(unit.New),
		"NewDimension":         reflect.ValueOf(unit.NewDimension),
		"Newton":               reflect.ValueOf(unit.Newton),
		"Newtonmetre":          reflect.ValueOf(unit.Newtonmetre),
		"Ohm":                  reflect.ValueOf(unit.Ohm),
		"Pascal":               reflect.ValueOf(unit.Pascal),
		"Peta":                 reflect.ValueOf(constant.MakeFromLiteral("1000000000000000", token.FLOAT, 0)),
		"Pico":                 reflect.ValueOf(constant.MakeFromLiteral("1.000000000000000000002600712391416405251921920840571522681727856e-12", token.FLOAT, 0)),
		"Rad":                  reflect.ValueOf(unit.Rad),
		"Second":               reflect.ValueOf(unit.Second),
		"Siemens":              reflect.ValueOf(unit.Siemens),
		"Sievert":              reflect.ValueOf(unit.Sievert),
		"SymbolExists":         reflect.ValueOf(unit.SymbolExists),
		"TemperatureDim":       reflect.ValueOf(unit.TemperatureDim),
		"Tera":                 reflect.ValueOf(constant.MakeFromLiteral("1000000000000", token.FLOAT, 0)),
		"Tesla":                reflect.ValueOf(unit.Tesla),
		"TimeDim":              reflect.ValueOf(unit.TimeDim),
		"Volt":                 reflect.ValueOf(unit.Volt),
		"Watt":                 reflect.ValueOf(unit.Watt),
		"Weber":                reflect.ValueOf(unit.Weber),
		"Yocto":                reflect.ValueOf(constant.MakeFromLiteral("9.9999999999999999999999943023239813783515427641604476656945703180777466584586845e-25", token.FLOAT, 0)),
		"Yotta":                reflect.ValueOf(constant.MakeFromLiteral("1000000000000000000000000", token.FLOAT, 0)),
		"Zepto":                reflect.ValueOf(constant.MakeFromLiteral("1.000000000000000000000012633091366698220994385930712326248006438025758e-21", token.FLOAT, 0)),
		"Zetta":                reflect.ValueOf(constant.MakeFromLiteral("1000000000000000000000", token.FLOAT, 0)),

		// type definitions
		"AbsorbedRadioactiveDose":   reflect.ValueOf((*unit.AbsorbedRadioactiveDose)(nil)),
		"Acceleration":              reflect.ValueOf((*unit.Acceleration)(nil)),
		"Angle":                     reflect.ValueOf((*unit.Angle)(nil)),
		"Area":                      reflect.ValueOf((*unit.Area)(nil)),
		"Capacitance":               reflect.ValueOf((*unit.Capacitance)(nil)),
		"Charge":                    reflect.ValueOf((*unit.Charge)(nil)),
		"Conductance":               reflect.ValueOf((*unit.Conductance)(nil)),
		"Current":                   reflect.ValueOf((*unit.Current)(nil)),
		"Dimension":                 reflect.ValueOf((*unit.Dimension)(nil)),
		"Dimensions":                reflect.ValueOf((*unit.Dimensions)(nil)),
		"Dimless":                   reflect.ValueOf((*unit.Dimless)(nil)),
		"Energy":                    reflect.ValueOf((*unit.Energy)(nil)),
		"EquivalentRadioactiveDose": reflect.ValueOf((*unit.EquivalentRadioactiveDose)(nil)),
		"Force":                     reflect.ValueOf((*unit.Force)(nil)),
		"Frequency":                 reflect.ValueOf((*unit.Frequency)(nil)),
		"Inductance":                reflect.ValueOf((*unit.Inductance)(nil)),
		"Length":                    reflect.ValueOf((*unit.Length)(nil)),
		"LuminousIntensity":         reflect.ValueOf((*unit.LuminousIntensity)(nil)),
		"MagneticFlux":              reflect.ValueOf((*unit.MagneticFlux)(nil)),
		"MagneticFluxDensity":       reflect.ValueOf((*unit.MagneticFluxDensity)(nil)),
		"Mass":                      reflect.ValueOf((*unit.Mass)(nil)),
		"Mole":                      reflect.ValueOf((*unit.Mole)(nil)),
		"Power":                     reflect.ValueOf((*unit.Power)(nil)),
		"Pressure":                  reflect.ValueOf((*unit.Pressure)(nil)),
		"Radioactivity":             reflect.ValueOf((*unit.Radioactivity)(nil)),
		"Resistance":                reflect.ValueOf((*unit.Resistance)(nil)),
		"Temperature":               reflect.ValueOf((*unit.Temperature)(nil)),
		"Time":                      reflect.ValueOf((*unit.Time)(nil)),
		"Torque":                    reflect.ValueOf((*unit.Torque)(nil)),
		"Unit":                      reflect.ValueOf((*unit.Unit)(nil)),
		"Uniter":                    reflect.ValueOf((*unit.Uniter)(nil)),
		"Velocity":                  reflect.ValueOf((*unit.Velocity)(nil)),
		"Voltage":                   reflect.ValueOf((*unit.Voltage)(nil)),
		"Volume":                    reflect.ValueOf((*unit.Volume)(nil)),

		// interface wrapper definitions
		"_Uniter": reflect.ValueOf((*_gonum_org_v1_gonum_unit_Uniter)(nil)),
	}
}

// _gonum_org_v1_gonum_unit_Uniter is an interface wrapper for Uniter type
type _gonum_org_v1_gonum_unit_Uniter struct {
	WUnit func() *unit.Unit
}

func (W _gonum_org_v1_gonum_unit_Uniter) Unit() *unit.Unit { return W.WUnit() }
