// Code generated by 'github.com/containous/yaegi/extract gonum.org/v1/gonum/stat/distmat'. DO NOT EDIT.

// Copyright ©2019 The Gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// +build go1.15,!go1.16

package yaegi

import (
	"reflect"

	"gonum.org/v1/gonum/stat/distmat"
)

func init() {
	Symbols["gonum.org/v1/gonum/stat/distmat"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewUniformPermutation": reflect.ValueOf(distmat.NewUniformPermutation),
		"NewWishart":            reflect.ValueOf(distmat.NewWishart),

		// type definitions
		"UniformPermutation": reflect.ValueOf((*distmat.UniformPermutation)(nil)),
		"Wishart":            reflect.ValueOf((*distmat.Wishart)(nil)),
	}
}
