// Code generated by 'goexports gonum.org/v1/gonum/num/dual'. DO NOT EDIT.

// Copyright ©2019 The Gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// +build go1.14,!go1.15

package yaegi

import (
	"reflect"

	"gonum.org/v1/gonum/num/dual"
)

func init() {
	Symbols["gonum.org/v1/gonum/num/dual"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Abs":     reflect.ValueOf(dual.Abs),
		"Acos":    reflect.ValueOf(dual.Acos),
		"Acosh":   reflect.ValueOf(dual.Acosh),
		"Add":     reflect.ValueOf(dual.Add),
		"Asin":    reflect.ValueOf(dual.Asin),
		"Asinh":   reflect.ValueOf(dual.Asinh),
		"Atan":    reflect.ValueOf(dual.Atan),
		"Atanh":   reflect.ValueOf(dual.Atanh),
		"Cos":     reflect.ValueOf(dual.Cos),
		"Cosh":    reflect.ValueOf(dual.Cosh),
		"Exp":     reflect.ValueOf(dual.Exp),
		"Inv":     reflect.ValueOf(dual.Inv),
		"Log":     reflect.ValueOf(dual.Log),
		"Mul":     reflect.ValueOf(dual.Mul),
		"Pow":     reflect.ValueOf(dual.Pow),
		"PowReal": reflect.ValueOf(dual.PowReal),
		"Scale":   reflect.ValueOf(dual.Scale),
		"Sin":     reflect.ValueOf(dual.Sin),
		"Sinh":    reflect.ValueOf(dual.Sinh),
		"Sqrt":    reflect.ValueOf(dual.Sqrt),
		"Sub":     reflect.ValueOf(dual.Sub),
		"Tan":     reflect.ValueOf(dual.Tan),
		"Tanh":    reflect.ValueOf(dual.Tanh),

		// type definitions
		"Number": reflect.ValueOf((*dual.Number)(nil)),
	}
}
