// Code generated by 'github.com/containous/yaegi/extract gonum.org/v1/gonum/cmplxs/cscalar'. DO NOT EDIT.

// Copyright ©2019 The Gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build go1.15 && !go1.16
// +build go1.15,!go1.16

package yaegi

import (
	"reflect"

	"gonum.org/v1/gonum/cmplxs/cscalar"
)

func init() {
	Symbols["gonum.org/v1/gonum/cmplxs/cscalar"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"EqualWithinAbs":      reflect.ValueOf(cscalar.EqualWithinAbs),
		"EqualWithinAbsOrRel": reflect.ValueOf(cscalar.EqualWithinAbsOrRel),
		"EqualWithinRel":      reflect.ValueOf(cscalar.EqualWithinRel),
		"ParseWithNA":         reflect.ValueOf(cscalar.ParseWithNA),
		"Round":               reflect.ValueOf(cscalar.Round),
		"RoundEven":           reflect.ValueOf(cscalar.RoundEven),
		"Same":                reflect.ValueOf(cscalar.Same),
	}
}
