// Code generated by 'github.com/containous/yaegi/extract gonum.org/v1/gonum/graph/encoding/dot'. DO NOT EDIT.

// Copyright ©2019 The Gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build go1.15 && !go1.16
// +build go1.15,!go1.16

package yaegi

import (
	"reflect"

	"gonum.org/v1/gonum/graph"
	"gonum.org/v1/gonum/graph/encoding"
	"gonum.org/v1/gonum/graph/encoding/dot"
)

func init() {
	Symbols["gonum.org/v1/gonum/graph/encoding/dot"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Marshal":        reflect.ValueOf(dot.Marshal),
		"MarshalMulti":   reflect.ValueOf(dot.MarshalMulti),
		"Unmarshal":      reflect.ValueOf(dot.Unmarshal),
		"UnmarshalMulti": reflect.ValueOf(dot.UnmarshalMulti),

		// type definitions
		"AttributeSetters": reflect.ValueOf((*dot.AttributeSetters)(nil)),
		"Attributers":      reflect.ValueOf((*dot.Attributers)(nil)),
		"DOTIDSetter":      reflect.ValueOf((*dot.DOTIDSetter)(nil)),
		"Graph":            reflect.ValueOf((*dot.Graph)(nil)),
		"MultiStructurer":  reflect.ValueOf((*dot.MultiStructurer)(nil)),
		"MultiSubgrapher":  reflect.ValueOf((*dot.MultiSubgrapher)(nil)),
		"Multigraph":       reflect.ValueOf((*dot.Multigraph)(nil)),
		"Node":             reflect.ValueOf((*dot.Node)(nil)),
		"PortSetter":       reflect.ValueOf((*dot.PortSetter)(nil)),
		"Porter":           reflect.ValueOf((*dot.Porter)(nil)),
		"Structurer":       reflect.ValueOf((*dot.Structurer)(nil)),
		"Subgrapher":       reflect.ValueOf((*dot.Subgrapher)(nil)),

		// interface wrapper definitions
		"_AttributeSetters": reflect.ValueOf((*_gonum_org_v1_gonum_graph_encoding_dot_AttributeSetters)(nil)),
		"_Attributers":      reflect.ValueOf((*_gonum_org_v1_gonum_graph_encoding_dot_Attributers)(nil)),
		"_DOTIDSetter":      reflect.ValueOf((*_gonum_org_v1_gonum_graph_encoding_dot_DOTIDSetter)(nil)),
		"_Graph":            reflect.ValueOf((*_gonum_org_v1_gonum_graph_encoding_dot_Graph)(nil)),
		"_MultiStructurer":  reflect.ValueOf((*_gonum_org_v1_gonum_graph_encoding_dot_MultiStructurer)(nil)),
		"_MultiSubgrapher":  reflect.ValueOf((*_gonum_org_v1_gonum_graph_encoding_dot_MultiSubgrapher)(nil)),
		"_Multigraph":       reflect.ValueOf((*_gonum_org_v1_gonum_graph_encoding_dot_Multigraph)(nil)),
		"_Node":             reflect.ValueOf((*_gonum_org_v1_gonum_graph_encoding_dot_Node)(nil)),
		"_PortSetter":       reflect.ValueOf((*_gonum_org_v1_gonum_graph_encoding_dot_PortSetter)(nil)),
		"_Porter":           reflect.ValueOf((*_gonum_org_v1_gonum_graph_encoding_dot_Porter)(nil)),
		"_Structurer":       reflect.ValueOf((*_gonum_org_v1_gonum_graph_encoding_dot_Structurer)(nil)),
		"_Subgrapher":       reflect.ValueOf((*_gonum_org_v1_gonum_graph_encoding_dot_Subgrapher)(nil)),
	}
}

// _gonum_org_v1_gonum_graph_encoding_dot_AttributeSetters is an interface wrapper for AttributeSetters type
type _gonum_org_v1_gonum_graph_encoding_dot_AttributeSetters struct {
	WDOTAttributeSetters func() (graph encoding.AttributeSetter, node encoding.AttributeSetter, edge encoding.AttributeSetter)
}

func (W _gonum_org_v1_gonum_graph_encoding_dot_AttributeSetters) DOTAttributeSetters() (graph encoding.AttributeSetter, node encoding.AttributeSetter, edge encoding.AttributeSetter) {
	return W.WDOTAttributeSetters()
}

// _gonum_org_v1_gonum_graph_encoding_dot_Attributers is an interface wrapper for Attributers type
type _gonum_org_v1_gonum_graph_encoding_dot_Attributers struct {
	WDOTAttributers func() (graph encoding.Attributer, node encoding.Attributer, edge encoding.Attributer)
}

func (W _gonum_org_v1_gonum_graph_encoding_dot_Attributers) DOTAttributers() (graph encoding.Attributer, node encoding.Attributer, edge encoding.Attributer) {
	return W.WDOTAttributers()
}

// _gonum_org_v1_gonum_graph_encoding_dot_DOTIDSetter is an interface wrapper for DOTIDSetter type
type _gonum_org_v1_gonum_graph_encoding_dot_DOTIDSetter struct {
	WSetDOTID func(id string)
}

func (W _gonum_org_v1_gonum_graph_encoding_dot_DOTIDSetter) SetDOTID(id string) { W.WSetDOTID(id) }

// _gonum_org_v1_gonum_graph_encoding_dot_Graph is an interface wrapper for Graph type
type _gonum_org_v1_gonum_graph_encoding_dot_Graph struct {
	WDOTID          func() string
	WEdge           func(uid int64, vid int64) graph.Edge
	WFrom           func(id int64) graph.Nodes
	WHasEdgeBetween func(xid int64, yid int64) bool
	WNode           func(id int64) graph.Node
	WNodes          func() graph.Nodes
}

func (W _gonum_org_v1_gonum_graph_encoding_dot_Graph) DOTID() string { return W.WDOTID() }
func (W _gonum_org_v1_gonum_graph_encoding_dot_Graph) Edge(uid int64, vid int64) graph.Edge {
	return W.WEdge(uid, vid)
}
func (W _gonum_org_v1_gonum_graph_encoding_dot_Graph) From(id int64) graph.Nodes { return W.WFrom(id) }
func (W _gonum_org_v1_gonum_graph_encoding_dot_Graph) HasEdgeBetween(xid int64, yid int64) bool {
	return W.WHasEdgeBetween(xid, yid)
}
func (W _gonum_org_v1_gonum_graph_encoding_dot_Graph) Node(id int64) graph.Node { return W.WNode(id) }
func (W _gonum_org_v1_gonum_graph_encoding_dot_Graph) Nodes() graph.Nodes       { return W.WNodes() }

// _gonum_org_v1_gonum_graph_encoding_dot_MultiStructurer is an interface wrapper for MultiStructurer type
type _gonum_org_v1_gonum_graph_encoding_dot_MultiStructurer struct {
	WStructure func() []dot.Multigraph
}

func (W _gonum_org_v1_gonum_graph_encoding_dot_MultiStructurer) Structure() []dot.Multigraph {
	return W.WStructure()
}

// _gonum_org_v1_gonum_graph_encoding_dot_MultiSubgrapher is an interface wrapper for MultiSubgrapher type
type _gonum_org_v1_gonum_graph_encoding_dot_MultiSubgrapher struct {
	WSubgraph func() graph.Multigraph
}

func (W _gonum_org_v1_gonum_graph_encoding_dot_MultiSubgrapher) Subgraph() graph.Multigraph {
	return W.WSubgraph()
}

// _gonum_org_v1_gonum_graph_encoding_dot_Multigraph is an interface wrapper for Multigraph type
type _gonum_org_v1_gonum_graph_encoding_dot_Multigraph struct {
	WDOTID          func() string
	WFrom           func(id int64) graph.Nodes
	WHasEdgeBetween func(xid int64, yid int64) bool
	WLines          func(uid int64, vid int64) graph.Lines
	WNode           func(id int64) graph.Node
	WNodes          func() graph.Nodes
}

func (W _gonum_org_v1_gonum_graph_encoding_dot_Multigraph) DOTID() string { return W.WDOTID() }
func (W _gonum_org_v1_gonum_graph_encoding_dot_Multigraph) From(id int64) graph.Nodes {
	return W.WFrom(id)
}
func (W _gonum_org_v1_gonum_graph_encoding_dot_Multigraph) HasEdgeBetween(xid int64, yid int64) bool {
	return W.WHasEdgeBetween(xid, yid)
}
func (W _gonum_org_v1_gonum_graph_encoding_dot_Multigraph) Lines(uid int64, vid int64) graph.Lines {
	return W.WLines(uid, vid)
}
func (W _gonum_org_v1_gonum_graph_encoding_dot_Multigraph) Node(id int64) graph.Node {
	return W.WNode(id)
}
func (W _gonum_org_v1_gonum_graph_encoding_dot_Multigraph) Nodes() graph.Nodes { return W.WNodes() }

// _gonum_org_v1_gonum_graph_encoding_dot_Node is an interface wrapper for Node type
type _gonum_org_v1_gonum_graph_encoding_dot_Node struct {
	WDOTID func() string
}

func (W _gonum_org_v1_gonum_graph_encoding_dot_Node) DOTID() string { return W.WDOTID() }

// _gonum_org_v1_gonum_graph_encoding_dot_PortSetter is an interface wrapper for PortSetter type
type _gonum_org_v1_gonum_graph_encoding_dot_PortSetter struct {
	WSetFromPort func(port string, compass string) error
	WSetToPort   func(port string, compass string) error
}

func (W _gonum_org_v1_gonum_graph_encoding_dot_PortSetter) SetFromPort(port string, compass string) error {
	return W.WSetFromPort(port, compass)
}
func (W _gonum_org_v1_gonum_graph_encoding_dot_PortSetter) SetToPort(port string, compass string) error {
	return W.WSetToPort(port, compass)
}

// _gonum_org_v1_gonum_graph_encoding_dot_Porter is an interface wrapper for Porter type
type _gonum_org_v1_gonum_graph_encoding_dot_Porter struct {
	WFromPort func() (port string, compass string)
	WToPort   func() (port string, compass string)
}

func (W _gonum_org_v1_gonum_graph_encoding_dot_Porter) FromPort() (port string, compass string) {
	return W.WFromPort()
}
func (W _gonum_org_v1_gonum_graph_encoding_dot_Porter) ToPort() (port string, compass string) {
	return W.WToPort()
}

// _gonum_org_v1_gonum_graph_encoding_dot_Structurer is an interface wrapper for Structurer type
type _gonum_org_v1_gonum_graph_encoding_dot_Structurer struct {
	WStructure func() []dot.Graph
}

func (W _gonum_org_v1_gonum_graph_encoding_dot_Structurer) Structure() []dot.Graph {
	return W.WStructure()
}

// _gonum_org_v1_gonum_graph_encoding_dot_Subgrapher is an interface wrapper for Subgrapher type
type _gonum_org_v1_gonum_graph_encoding_dot_Subgrapher struct {
	WSubgraph func() graph.Graph
}

func (W _gonum_org_v1_gonum_graph_encoding_dot_Subgrapher) Subgraph() graph.Graph {
	return W.WSubgraph()
}
