// Code generated by 'goexports gonum.org/v1/gonum/spatial/r1'. DO NOT EDIT.

// Copyright ©2019 The Gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// +build go1.12,!go1.13

package yaegi

import (
	"reflect"

	"gonum.org/v1/gonum/spatial/r1"
)

func init() {
	Symbols["gonum.org/v1/gonum/spatial/r1"] = map[string]reflect.Value{
		// type definitions
		"Interval": reflect.ValueOf((*r1.Interval)(nil)),
	}
}
