sudo: false

os:
 - linux
 - osx
 - windows

language: go

# Versions of go that are explicitly supported by gonum plus go tip.
go:
 - 1.12.x
 - 1.11.x
 - 1.10.x
 - master

env:
 global:
  - GO111MODULE=on

matrix:
 fast_finish: true
 exclude:
  - os: windows
    go: 1.11.x
  - os: windows
    go: 1.10.x
  - os: windows
    go: master
 allow_failures:
  - go: master

before_install:
 - ${TRAVIS_BUILD_DIR}/.travis/run-parts ${TRAVIS_BUILD_DIR}/.travis/deps.d/${TRAVIS_OS_NAME}

go_import_path: gonum.org/v1/exp

# Get deps, build, test, and ensure the code is gofmt'ed.
# If we are building as gonum, then we have access to the coveralls api key, so we can run coverage as well.
script:
 - ${TRAVIS_BUILD_DIR}/.travis/run-parts ${TRAVIS_BUILD_DIR}/.travis/run.d/${TRAVIS_OS_NAME}
