name: CI

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    strategy:
      matrix:
        # Do not move this line; it is referred to by README.md.
        # Versions of Go that are explicitly supported by Gonum.
        go-version: [1.24.x, 1.23.x]
        # macOS is omitted due to rings failing for float precision
        # reasons. Fixing this requires updating plot dep version
        # but this brings a whole heap of other issues that I'm
        # just don't have time for right now.
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    env:
        GOPATH: ${{ github.workspace }}
    defaults:
        run:
            working-directory: ${{ env.GOPATH }}/src/gonum.org/v1/exp

    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v4
      with:
          path: ${{ env.GOPATH }}/src/gonum.org/v1/exp

    - name: Cache-Go
      uses: actions/cache@v4
      with:
        # In order:
        # * Module download cache 
        # * Build cache (Linux)
        # * Build cache (Mac)
        # * Build cache (Windows)
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          '%LocalAppData%\go-build'
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

    - name: Test
      run: |
        ./.github/workflows/script.d/test.sh

    - name: Coverage
      if: matrix.platform == 'ubuntu-latest'
      run: |
        ./.github/workflows/script.d/test-coverage.sh

    - name: Upload-Coverage
      if: matrix.platform == 'ubuntu-latest'
      uses: codecov/codecov-action@v1
